language: python
python:
  - "3.5"
  - "3.6"
addons:
  postgresql: "9.4"
before_install:
  - pip install pycodestyle
  - pycodestyle --exclude=tests *.py press
  - pycodestyle --max-line-length=200 press/tests

  - sudo apt-get update
  # remove zope.interface installed from aptitude
  - sudo apt-get purge python-zope.interface

  # * Install the 'plpython' extension language
  - sudo apt-get install postgresql-plpython-9.4
  # * Install the 'plxslt' extension language
  - sudo apt-get install libxml2-dev libxslt-dev postgresql-server-dev-9.4
  - git clone https://github.com/petere/plxslt.git
  - cd plxslt && sudo make && sudo make install && cd ..
  # * Install session_exec
  - git clone https://github.com/okbob/session_exec
  - cd session_exec && make USE_PGXS=1 -e && sudo make USE_PGXS=1 -e install && cd ..
  # * Install rhaptos.cnxmlutils
  # - git clone https://github.com/Connexions/rhaptos.cnxmlutils.git
  # - cd rhaptos.cnxmlutils && python setup.py install && cd ..

  # Install the coverage utility and codecov reporting utility
  - pip install pytest pytest-cov
  - pip install codecov
install:
  - pip install .
before_script:
  # Set up postgres roles
  - sudo -u postgres psql -d postgres -c "CREATE USER tester WITH SUPERUSER PASSWORD 'tester';"
  # Set up the database
  - sudo -u postgres createdb -O tester testing
script:
  # This is the same as `python setup.py test` with a coverage wrapper.
  - py.test --cov-config .coveragerc --cov=press
after_success:
  # Report test coverage to codecov.io
  - codecov
notifications:
  email: false
