version: '2'
# If you have modifications, put those in docker-compose.override.yml
# See also, https://docs.docker.com/compose/extends/#multiple-compose-files
services:
  # Our services:
  app:
    build: .
    volumes:
      - ./docs:/app/docs:z
      - ./press:/app/press:z
      - ./tests:/app/tests:z
      - ./htmlcov:/app/htmlcov:z
      - ./var:/app/var:z
    environment:
      - SHARED_DIR=/app/var
  db:
    image: openstax/cnx-db:1.5.1
    ports:
      - "5432:5432"
    environment:
      - DB_URL=postgresql://rhaptos@/repository
      - DB_SUPER_URL=postgresql://rhaptos_admin@/repository
  web:
    extends:
      service: app
    command: gunicorn -b 0.0.0.0:6543 --access-logfile - --error-logfile - -n press --reload wsgi:app
    ports:
      - "80:6543"
    links:
      - db
    environment:
      - SHARED_DIR=/app/var
      - DB_URL=postgresql://rhaptos@db/repository
      - DB_SUPER_URL=postgresql://rhaptos_admin@db/repository
